/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef multi_CONSTANTS_H
#define multi_CONSTANTS_H

#include "multi_types.h"

namespace tutorial {

class multiConstants {
 public:
  multiConstants();

};

extern const multiConstants g_multi_constants;

} // namespace

#endif
