/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "multi_constants.h"

namespace tutorial {

const multiConstants g_multi_constants;

multiConstants::multiConstants() {
}

} // namespace

